Add self-admitted technical debt calculation
npms-io/npms-analyzer pull request #116
Opened 2017-01-08 21:08 UTC by suhaibtamimi

This is a pull request to calculate the Technical Debt matrix based on the developers' comments in their source code.

I have added the matrix to the quality result but still not calculated in the final value of the quality measurement.

2017-01-09 22:36 UTC, satazor commented
This looks cool! Will review next weekend, out of time atm.

2017-01-27 23:47 UTC, suhaibtamimi commented
Hey guys,
Do you have a chance to look into this!

Have a good weekend :)

2017-04-01 21:44 UTC, satazor requested changes
Additionally, you are missing adding the `technicalDebts` to the score calculation. Do not forget that the more the debts, the lower the score should be. Probably the evaluation should reflect this.. perhaps should be `1 - debts.percent`.

2017-04-01 21:44 UTC, satazor commented on lib/analyze/evaluate/quality.js
> +    return collected.source.technicalDebts
Can you add a `;` at the end?

2017-04-01 21:56 UTC, suhaibtamimi commented on lib/analyze/evaluate/quality.js
> +    return collected.source.technicalDebts
yes, sure :)

2017-04-01 22:48 UTC, satazor commented
@suhaibtamimi Check my other comment above.

2017-04-02 00:13 UTC, suhaibtamimi commented
@satazor The requested changes are ready.

2017-04-02 08:47 UTC, satazor approved these changes

2017-04-02 08:49 UTC, satazor commented
@suhaibtamimi I think this is almost ready! I would just like to request one further change because I think it makes sense: instead of having `technicalDebts` in evaluation & score, what if we had `code`? This way we could group code related evaluation together, just like we do with `carefulness`, `health`, etc. For instance, `code` could evaluate technical debts, code complexity, and other code related metrics. Makes sense?

What do you think @atduarte ?

2017-04-02 16:20 UTC, suhaibtamimi commented
I agree it makes sense; I did move the `technicalDebts` evaluation under `code` category.

2023-04-07 15:57 UTC, closed without merging